"""empty message
Revision ID: 667a4a37a5a6
Revises:
Create Date: 2020-05-21 01:24:17.919856
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667a4a37a5a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(length=255), nullable=False),
    sa.Column('style_name', sa.String(length=255), nullable=False),
    sa.Column('recommend', sa.String(length=255), nullable=False),
    sa.Column('age', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_beer_index', table_name='beer_x')
    op.drop_table('beer_x')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer_x',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('style_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommend', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('age', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_beer_index', 'beer_x', ['index'], unique=False)
    op.drop_table('beer')
    # ### end Alembic commands ###
